// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type InsertShppcstPlcyRequestParams = {
  requestShppcstPlcyInsert: {
    shppcstId?: string;
    shppcstPlcyDivCd: string;
    shppcstAplUnitCd: string;
    prpayCodDivCd: string;
    shppcstExmpCritnAmt?: number;
    shppcst: number;
    shppcstCntt?: string;
    bascPlcyYn: string;
    shppcstAplYn: string;
  };
};

export type InsertShppcstPlcyResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    shppcstId?: string;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: InsertShppcstPlcyRequestParams): Promise<Response<InsertShppcstPlcyResponseParams>> {
    return await this.client<InsertShppcstPlcyResponseParams>("venInfo/0.1/insertShppcstPlcy.ssg", {
      method: "post",
      json: params,
    });
  }
}
