// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type InsertItemRequestParams = {
  insertItem?: {
    itemNm: string;
    mtlglItemInfos?: Array<{
      mtlglItem?: {
        langDivCd: string;
        mtlglItemNm?: string;
      };
    }>;
    mdlNm?: string;
    brandId: string;
    stdCtgId: string;
    sites?: Array<{
      site?: {
        siteNo: string;
        sellStatCd: string;
      };
    }>;
    itemAplRngTypeCd?: string;
    b2eAplRngCd?: string;
    b2cAplRngCd?: string;
    itemChrctDivCd: string;
    itemChrctDtlCd: string;
    exusItemDivCd: string;
    exusItemDtlCd: string;
    dispAplRngTypeCd: string;
    speSalestrNo?: string;
    itemMngPropClsId: string;
    ItemMngAttrs?: Array<{
      ItemMngAttr?: {
        itemMngPropId: string;
        itemMngCntt: string;
      };
    }>;
    manufcoNm: string;
    prodManufCntryId: string;
    dispCtgs?: Array<{
      dispCtg?: {
        siteNo: string;
        dispCtgId: string;
      };
    }>;
    dispStrtDts: string;
    dispEndDts: string;
    spDispCtgs?: Array<{
      dispCtg?: {
        siteNo: string;
        dispCtgId: string;
      };
    }>;
    srchPsblYn?: string;
    itemSrchwdNm?: string;
    aplMbrGrdCd?: string;
    minOnetOrdPsblQty: number;
    maxOnetOrdPsblQty: number;
    max1dyOrdPsblQty: number;
    adultItemTypeCd: string;
    hriskItemYn: string;
    nitmAplYn: string;
    sellPnts?: Array<{
      sellPnt?: {
        siteNo: string;
        sellpntNm: string;
        dispStrtDts: string;
        dispEndDts: string;
        useYn: "Yes" | "No";
      };
    }>;
    sellCapaUnitCd?: string;
    sellTotCapa?: number;
    sellUnitCapa?: number;
    sellUnitQty?: number;
    buyFrmCd: string;
    txnDivCd: string;
    prcMngMthd?: string;
    salesPrcInfos?: Array<{
      uitemPrc?: {
        splprc: number;
        sellprc: number;
        mrgrt: number;
      };
    }>;
    b2ePrcAplTgts?: Array<{
      b2ePrcAplTgt?: {
        b2eMbrcoId: string;
        b2eSplprc: number;
        b2eSellprc: number;
        b2eMrgrt: number;
      };
    }>;
    invMngYn: string;
    baseInvQty: number;
    invQtyMarkgYn: string;
    rsvSaleInfo?: {
      aplStrtDt: string;
      aplEndDt: string;
      whoutStrtDt: string;
      rstctInvQty: number;
    };
    itemSellTypeCd: string;
    itemSellTypeDtlCd: string;
    barcd?: string;
    uitemAttr?: {
      uitemCacOptnYn: string;
      uitemOptnChoiTypeCd1: string;
      uitemOptnExpsrTypeCd1: string;
      uitemOptnChoiTypeCd2?: string;
      uitemOptnExpsrTypeCd2?: string;
      uitemOptnChoiTypeCd3?: string;
      uitemOptnExpsrTypeCd3?: string;
      uitemOptnChoiTypeCd4?: string;
      uitemOptnExpsrTypeCd4?: string;
      uitemOptnChoiTypeCd5?: string;
      uitemOptnExpsrTypeCd5?: string;
    };
    uitems?: Array<{
      uitem?: {
        tempUitemId: string;
        barcd?: string;
        uitemOptnTypeNm1: string;
        uitemOptnNm1: string;
        uitemOptnTypeNm2?: string;
        uitemOptnNm2?: string;
        uitemOptnTypeNm3?: string;
        uitemOptnNm3?: string;
        uitemOptnTypeNm4?: string;
        uitemOptnNm4?: string;
        uitemOptnTypeNm5?: string;
        uitemOptnNm5?: string;
        baseInvQty?: number;
        rstctInvQty?: number;
        useYn: "Yes" | "No";
        splVenItemId?: string;
      };
    }>;
    uitemOptnAddts?: Array<{
      uitemOptnAddt: {
        uitemOptnNm: string;
        uitemOptnNo: string;
        uitemOptnIptTypeCd: string;
        dataFileNm: string;
        useYn: "Yes" | "No";
      };
    }>;
    itemOrdOptns?: Array<{
      itemOrdOptn?: {
        addOrdOptnSeq: string;
        addOrdOptnNm: string;
        addOrdOptnMndtyYn?: string;
      };
    }>;
    uitemEaitemOptnCac?: {
      eaitemOptnCacNm1?: string;
      eaitemMinCacUnitVal1?: number;
      eaitemMaxCacUnitVal1?: number;
      cmakeMesurUnitCd1?: string;
      eaitemOptnCacNm2?: string;
      eaitemMinCacUnitVal2?: number;
      eaitemMaxCacUnitVal2?: number;
      purchUnitQty?: number;
      punitSellprc?: number;
    };
    uitemPluralPrcs?: Array<{
      uitemPrc?: {
        tempUitemId: string;
        splprc: number;
        sellprc: number;
        mrgrt: number;
      };
    }>;
    shppItemDivCd: string;
    exprtCntryId?: string;
    retExchPsblYn: string;
    shppMainCd: string;
    shppMthdCd: string;
    mareaShppYn: string;
    jejuShppDisabYn: string;
    ismtarShppDisabYn: string;
    shppRqrmDcnt: number;
    shppRqrmDcntChngRsnCntt: string;
    splVenItemId?: string;
    whoutShppcstId: string;
    retShppcstId: string;
    ismtarAddShppcstId?: string;
    jejuAddShppcstId?: string;
    whoutAddrId: string;
    snbkAddrId: string;
    itemTotWgt?: number;
    hopeShppDdDivCd?: string;
    hopeShppDdEndDts?: string;
    itemImgs?: Array<{
      imgInfo?: {
        dataSeq: number;
        dataFileNm: string;
        rplcTextNm: string;
      };
    }>;
    qualityViewImgs?: Array<{
      imgInfo?: {
        dataSeq: number;
        dataFileNm: string;
        rplcTextNm: string;
      };
    }>;
    itemDesc: string;
    sizeDesc?: string;
    purchGuideCntt?: string;
    asMemoCntt?: string;
    qualityFiles?: Array<{
      qualityFile?: {
        itemDescDivCd: string;
        imgFileNm: string;
      };
    }>;
    certificationProps?: Array<{
      prop?: {
        itemAppePropClsId: string;
        itemAppePropId: string;
        itemAppePropCntt: string;
      };
    }>;
    giftPsblYn: string;
    shppMsgId?: string;
    vodExtnlPathUrl?: string;
    palimpItemYn: string;
    itemSellWayCd: string;
    itemStatTypeCd: string;
    whinNotiYn: string;
    fstPriceInfo?: {
      fstSellprc?: number;
      dataFileNm?: string;
    };
    book?: {
      isbn?: string;
      isbnExtensClsCd?: string;
      bookEngNm?: string;
      ortitlNm?: string;
      subtitlNm?: string;
      authorNm?: string;
      trltpeNm?: string;
      pubscoNm?: string;
      pageCntCntt?: string;
      pubsDt?: string;
      fxprc?: number;
      fxprcCurrCd?: string;
      appxBeingYn?: string;
      appxCntt?: string;
      tbcnttCntt?: string;
      authorIntroCntt?: string;
      trltpeIntroCntt?: string;
      prfaceCntt?: string;
      pubscoBkrevwCntt?: string;
      bookFxprcRegmAplYn?: string;
      bookItemDivCd?: string;
      limitGrdNm?: string;
      etcCntt?: string;
      addGuideCntt?: string;
      sellScr?: number;
      bookCpnNo?: string;
      bookCpnDcAmt?: number;
    };
    giftPackPsblYn?: string;
    ctvatInclYn?: string;
    tags?: Array<{
      tag?: {
        tagNm?: string;
      };
    }>;
    itemTripPropClsId?: string;
    itemTripAttrs?: Array<{
      itemTripAttr?: {
        itemTripPropId?: string;
        itemTripPropCntt?: string;
      };
    }>;
    luxprGantItemYn?: string;
    ipotRptNo?: string;
  };
};

export type InsertItemResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    itemId?: string;
    uitems?: Array<{
      uitem?: {
        uitemId: string;
        uitemOptnTypeNm1: string;
        uitemOptnNm1: string;
        uitemOptnTypeNm2?: string;
        uitemOptnNm2?: string;
        uitemOptnTypeNm3?: string;
        uitemOptnNm3?: string;
        uitemOptnTypeNm4?: string;
        uitemOptnNm4?: string;
        uitemOptnTypeNm5?: string;
        uitemOptnNm5?: string;
        baseInvQty?: number;
        rstctInvQty?: number;
        useYn: "Yes" | "No";
        splVenItemId?: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: InsertItemRequestParams): Promise<Response<InsertItemResponseParams>> {
    return await this.client<InsertItemResponseParams>("item/0.4/insertItem.ssg", {
      method: "post",
      json: params,
    });
  }
}
