// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type InsertImportPermitInfoRequestParams = {
  requestImportPermitInsert?: {
    dclrNo: string;
    blNo: string;
    cargMtNo: string;
    ldprCd: string;
    ocrUserYn?: string;
    atchFiles?: Array<{
      atchFile?: {
        fileNm: string;
      };
    }>;
  };
};

export type InsertImportPermitInfoResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    importPermitInfo?: Array<{ dclrNo: string; blNo: string; cargMtNo: string; ldprCd: string; inserted: string }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(
    params: InsertImportPermitInfoRequestParams,
  ): Promise<Response<InsertImportPermitInfoResponseParams>> {
    return await this.client<InsertImportPermitInfoResponseParams>("common/0.1/insertImportPermitInfo.ssg", {
      method: "post",
      json: params,
    });
  }
}
