// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListOrplcRequestParams = {
  orplcId?: string;
  orplcNm?: string;
  orplcYn?: string;
  manufCntryYn?: string;
  page?: number;
  pageSize?: number;
};

export type ListOrplcResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    orplcs?: Array<{
      orplc?: {
        orplcId: string;
        orplcNm: string;
        manufCntryYn: string;
        orplcYn: string;
        orplcDivNm: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListOrplcRequestParams): Promise<Response<ListOrplcResponseParams>> {
    return await this.client<ListOrplcResponseParams>("common/0.1/listOrplc.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
