// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetDptsItemListRequestParams = {
  itemId?: string;
  splVenItemId?: string;
  asisItemId?: string;
  itemNm?: string;
  sellStatCd?: string;
  itemSellTypeCd?: string;
  itemSellTypeDtlCd?: string;
  regDtsStart?: string;
  regDtsEnd?: string;
  siteNo?: string;
  page: number;
  pageSize: number;
  deptBaseSalestrNo?: string;
};

export type GetDptsItemListResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    items?: Array<{
      item?: {
        itemId: string;
        itemNm: string;
        sellStatCd: string;
        itemSellTypeCd: string;
        itemSellTypeDtlCd: string;
        siteNm: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: GetDptsItemListRequestParams): Promise<Response<GetDptsItemListResponseParams>> {
    return await this.client<GetDptsItemListResponseParams>("item/0.1/getItemList.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
