// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/index-generator.ts if you want to make any changes.

import * as displayCategory from "./display-category";
import * as getCommCdDtlc from "./get-comm-cd-dtlc";
import * as getDptsItemList from "./get-dpts-item-list";
import * as getImportPermitInfo from "./get-import-permit-info";
import * as getItemAppeAttrList from "./get-item-appe-attr-list";
import * as getItemAppeCertProps from "./get-item-appe-cert-props";
import * as getItemAttrPropDtlList from "./get-item-attr-prop-dtl-list";
import * as getItemAttrPropList from "./get-item-attr-prop-list";
import * as getItemChngDemandList from "./get-item-chng-demand-list";
import * as getItemList from "./get-item-list";
import * as getProhibitedWordList from "./get-prohibited-word-list";
import * as getTripPropCommCd from "./get-trip-prop-comm-cd";
import * as getVenShppMsgList from "./get-ven-shpp-msg-list";
import * as insertDeptItem from "./insert-dept-item";
import * as insertImportPermitInfo from "./insert-import-permit-info";
import * as insertItem from "./insert-item";
import * as insertShppcstPlcy from "./insert-shppcst-plcy";
import * as insertTourItem from "./insert-tour-item";
import * as listBrand from "./list-brand";
import * as listDispCtg from "./list-disp-ctg";
import * as listItemAppeProp from "./list-item-appe-prop";
import * as listItemMngProp from "./list-item-mng-prop";
import * as listItemMngPropCls from "./list-item-mng-prop-cls";
import * as listOrplc from "./list-orplc";
import * as listShppcstPlcy from "./list-shppcst-plcy";
import * as listSpecialSalestrNo from "./list-special-salestr-no";
import * as listStdCtgKeyPath from "./list-std-ctg-key-path";
import * as updateDeptItem from "./update-dept-item";
import * as updateItem from "./update-item";
import * as updateItemAppeProp from "./update-item-appe-prop";
import * as updateTourItem from "./update-tour-item";
import * as viewDptsItem from "./view-dpts-item";
import * as viewItem from "./view-item";
export { displayCategory };
export { getCommCdDtlc };
export { getDptsItemList };
export { getImportPermitInfo };
export { getItemAppeAttrList };
export { getItemAppeCertProps };
export { getItemAttrPropDtlList };
export { getItemAttrPropList };
export { getItemChngDemandList };
export { getItemList };
export { getProhibitedWordList };
export { getTripPropCommCd };
export { getVenShppMsgList };
export { insertDeptItem };
export { insertImportPermitInfo };
export { insertItem };
export { insertShppcstPlcy };
export { insertTourItem };
export { listBrand };
export { listDispCtg };
export { listItemAppeProp };
export { listItemMngProp };
export { listItemMngPropCls };
export { listOrplc };
export { listShppcstPlcy };
export { listSpecialSalestrNo };
export { listStdCtgKeyPath };
export { updateDeptItem };
export { updateItem };
export { updateItemAppeProp };
export { updateTourItem };
export { viewDptsItem };
export { viewItem };

export function createClients(key: string) {
  return {
    displayCategory: new displayCategory.Client(key),
    getCommCdDtlc: new getCommCdDtlc.Client(key),
    getDptsItemList: new getDptsItemList.Client(key),
    getImportPermitInfo: new getImportPermitInfo.Client(key),
    getItemAppeAttrList: new getItemAppeAttrList.Client(key),
    getItemAppeCertProps: new getItemAppeCertProps.Client(key),
    getItemAttrPropDtlList: new getItemAttrPropDtlList.Client(key),
    getItemAttrPropList: new getItemAttrPropList.Client(key),
    getItemChngDemandList: new getItemChngDemandList.Client(key),
    getItemList: new getItemList.Client(key),
    getProhibitedWordList: new getProhibitedWordList.Client(key),
    getTripPropCommCd: new getTripPropCommCd.Client(key),
    getVenShppMsgList: new getVenShppMsgList.Client(key),
    insertDeptItem: new insertDeptItem.Client(key),
    insertImportPermitInfo: new insertImportPermitInfo.Client(key),
    insertItem: new insertItem.Client(key),
    insertShppcstPlcy: new insertShppcstPlcy.Client(key),
    insertTourItem: new insertTourItem.Client(key),
    listBrand: new listBrand.Client(key),
    listDispCtg: new listDispCtg.Client(key),
    listItemAppeProp: new listItemAppeProp.Client(key),
    listItemMngProp: new listItemMngProp.Client(key),
    listItemMngPropCls: new listItemMngPropCls.Client(key),
    listOrplc: new listOrplc.Client(key),
    listShppcstPlcy: new listShppcstPlcy.Client(key),
    listSpecialSalestrNo: new listSpecialSalestrNo.Client(key),
    listStdCtgKeyPath: new listStdCtgKeyPath.Client(key),
    updateDeptItem: new updateDeptItem.Client(key),
    updateItem: new updateItem.Client(key),
    updateItemAppeProp: new updateItemAppeProp.Client(key),
    updateTourItem: new updateTourItem.Client(key),
    viewDptsItem: new viewDptsItem.Client(key),
    viewItem: new viewItem.Client(key),
  };
}
