// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetItemAppeAttrListRequestParams = { itemId: string };

export type GetItemAppeAttrListResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    itemAppeAttrs?: Array<{
      itemAppeAttr?: {
        itemAppePropId: string;
        itemAppePropCntt: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: GetItemAppeAttrListRequestParams): Promise<Response<GetItemAppeAttrListResponseParams>> {
    return await this.client<GetItemAppeAttrListResponseParams>("itemAttr/0.1/getItemAppeAttrList.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
