// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetTripPropCommCdRequestParams = { tripPropKind: string; page?: number; pageSize?: number };

export type GetTripPropCommCdResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    tripCommCds?: Array<{
      tripCommCd?: {
        tripCommCd: string;
        tripCommCdNm: string;
        tripCommCdEngNm?: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: GetTripPropCommCdRequestParams): Promise<Response<GetTripPropCommCdResponseParams>> {
    return await this.client<GetTripPropCommCdResponseParams>("common/0.1/getTripPropCommCd.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
