// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListItemAppePropRequestParams = { stdCtgId: string };

export type ListItemAppePropResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    itemAppeProps?: Array<{
      itemAppeProp?: {
        itemAppePropId: string;
        itemAppePropNm: string;
        itemAppePropTypeCd: string;
        itemAppePropDtlTypeCd: string;
        dispPrioyExpsrYn: string;
        mndtyYn: string;
        commCdDtlcList?: Array<{
          commCdDtlc?: {
            commCdNo?: string;
            commCdNm?: string;
          };
        }>;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListItemAppePropRequestParams): Promise<Response<ListItemAppePropResponseParams>> {
    return await this.client<ListItemAppePropResponseParams>("common/0.1/listItemAppeProp.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
