// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListBrandRequestParams = {
  brandId?: string;
  brandNm?: string;
  omBrandYn?: string;
  page?: number;
  pageSize?: number;
};

export type ListBrandResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    brands?: Array<{
      brand?: {
        brandId: string;
        brandNm: string;
        useYn: "Yes" | "No";
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListBrandRequestParams): Promise<Response<ListBrandResponseParams>> {
    return await this.client<ListBrandResponseParams>("venInfo/0.1/listBrand.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
