// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListSpecialSalestrNoRequestParams = { spctstrDivCd: string };

export type ListSpecialSalestrNoResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    salestrs?: Array<{
      specialSalestr?: {
        salestrNo: string;
        salestrNm: string;
        spctstrDivCd: string;
        spctstrDivNm: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListSpecialSalestrNoRequestParams): Promise<Response<ListSpecialSalestrNoResponseParams>> {
    return await this.client<ListSpecialSalestrNoResponseParams>("common/0.1/listSpecialSalestrNo.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
