// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetItemAttrPropListRequestParams = { stdCtgId?: string; dispCtgId?: string };

export type GetItemAttrPropListResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    itemAppeProps?: Array<{
      itemAppeProp?: {
        itemAppePropId: string;
        itemAppePropNm: string;
        maxIptVal: number;
        useYn: "Yes" | "No";
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: GetItemAttrPropListRequestParams): Promise<Response<GetItemAttrPropListResponseParams>> {
    return await this.client<GetItemAttrPropListResponseParams>("itemAttr/0.1/getItemAppePropTgtList.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
