// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListItemMngPropClsRequestParams = { itemMngPropClsId?: string };

export type ListItemMngPropClsResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    itemMngPropClss?: Array<{
      itemMngPropCls?: {
        itemMngPropClsId: string;
        itemMngPropClsNm: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListItemMngPropClsRequestParams): Promise<Response<ListItemMngPropClsResponseParams>> {
    return await this.client<ListItemMngPropClsResponseParams>("common/0.2/listItemMngPropCls.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
