// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetCommCdDtlcRequestParams = { commCd: string };

export type GetCommCdDtlcResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    commCdDtlc?: Array<{
      commCdDtlc?: {
        commCd: string;
        commCdNo: string;
        commCdNm: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: GetCommCdDtlcRequestParams): Promise<Response<GetCommCdDtlcResponseParams>> {
    return await this.client<GetCommCdDtlcResponseParams>("common/0.1/getCommCdDtlc.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
