// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetItemChngDemandListRequestParams = {
  itemId: string;
  itemrChngDemndDivCd?: string;
  chngDemndProcStatCd?: string;
};

export type GetItemChngDemandListResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    itemChngDemndList?: Array<{
      itemChngDemnd?: {
        itemrChngDemndDivCd: string;
        chngDemndProcStatCd: string;
        itemChngDemndDivNm: string;
        chngDemndProcStatNm: string;
        rjctRsnCntt?: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(
    params: GetItemChngDemandListRequestParams,
  ): Promise<Response<GetItemChngDemandListResponseParams>> {
    return await this.client<GetItemChngDemandListResponseParams>("item/0.1/getItemChngDemandList.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
