// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetImportPermitInfoRequestParams = { dclrNo: string; blNo: string };

export type GetImportPermitInfoResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    importPermitInfo?: Array<{ dclrNo: string; blNo: string; cargMtNo: string; ldprCd: string; inserted: string }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: GetImportPermitInfoRequestParams): Promise<Response<GetImportPermitInfoResponseParams>> {
    return await this.client<GetImportPermitInfoResponseParams>("common/0.1/getImportPermitInfo.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
