// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListStdCtgKeyPathRequestParams = {
  siteNo?: string;
  stdCgGrpCd?: string;
  stdCtgLclsId?: string;
  stdCtgMclsId?: string;
  stdCtgSclsId?: string;
  stdCtgDclsId?: string;
  page?: number;
  pageSize?: number;
};

export type ListStdCtgKeyPathResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    stdctgs?: Array<{
      stdctg?: {
        siteNo: string;
        siteNm: string;
        buyFrmCd: string;
        stdCtgGrpCd: string;
        stdCtgGrpNm: string;
        stdCtgLclsId: string;
        stdCtgLclsNm: string;
        stdCtgMclsId: string;
        stdCtgMclsNm: string;
        stdCtgSclsId: string;
        stdCtgSclsNm: string;
        stdCtgDclsId: string;
        stdCtgDclsNm: string;
        itemMngPropClsId?: string;
        itemMngPropClsNm?: string;
        txnPermitDivCd: string;
        txnPermitDivNm: string;
        itemTripPropClsId?: string;
        itemTripPropClsNm?: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListStdCtgKeyPathRequestParams): Promise<Response<ListStdCtgKeyPathResponseParams>> {
    return await this.client<ListStdCtgKeyPathResponseParams>("venInfo/0.2/listStdCtgKeyPath.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
