// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type UpdateDeptItemRequestParams = {
  updateItem?: {
    itemId?: string;
    itemNm?: string;
    mtlglItemInfos?: Array<{
      mtlglItem?: {
        langDivCd: string;
        mtlglItemNm?: string;
      };
    }>;
    mdlNm?: string;
    dpCode?: string;
    brandId?: string;
    salestrs: Array<{
      salestr: {
        salestrNo: string;
        shppMthdCd?: string;
        qshppPsblYn?: string;
        pickuItemYn?: string;
        giftPackPsblYn?: string;
      };
    }>;
    itemAplRngTypeCd?: string;
    b2eAplRngCd?: string;
    b2cAplRngCd?: string;
    itemChrctDivCd?: string;
    itemChrctDtlCd?: string;
    exusItemDivCd?: string;
    exusItemDtlCd?: string;
    dispAplRngTypeCd?: string;
    sellStatCd?: string;
    itemMngPropClsId?: string;
    ItemMngAttrs?: Array<{
      ItemMngAttr?: {
        itemMngPropId: string;
        itemMngCntt: string;
      };
    }>;
    manufcoNm?: string;
    prodManufCntryId?: string;
    dispCtgs: Array<{
      dispCtg: {
        siteNo: string;
        delYn?: string;
        dispCtgId: string;
      };
    }>;
    dispStrtDts: string;
    dispEndDts: string;
    spDispCtgs?: Array<{
      dispCtg?: {
        siteNo: string;
        delYn?: string;
        dispCtgId: string;
      };
    }>;
    srchPsblYn?: string;
    itemSrchwdNm?: string;
    aplMbrGrdCd?: string;
    minOnetOrdPsblQty?: number;
    maxOnetOrdPsblQty?: number;
    max1dyOrdPsblQty?: number;
    adultItemTypeCd: string;
    hriskItemYn?: string;
    nitmAplYn?: string;
    dptsNostrItemYn: string;
    crfwItemMarkYn: string;
    sellPnts?: Array<{
      sellPnt?: {
        siteNo: string;
        sellpntId: string;
        sellpntNm: string;
        dispStrtDts: string;
        dispEndDts: string;
        useYn: "Yes" | "No";
      };
    }>;
    itemAppeAttrs?: Array<{
      itemAppeAttr?: {
        itemAppePropId: string;
        itemAppePropCntt: string;
      };
    }>;
    sellCapaUnitCd?: string;
    sellTotCapa?: number;
    sellUnitCapa?: number;
    sellUnitQty?: number;
    salesPrcInfos?: Array<{
      uitemPrc?: {
        salestrNo: string;
        sellprc: number;
        prcDivCd: number;
      };
    }>;
    chgSalesPrcInfos?: Array<{
      uitemPrc?: {
        salestrNo: string;
        sellprc: number;
        prcDivCd: number;
        aplStrtDts: string;
      };
    }>;
    returnSalesPrcInfos?: Array<{
      uitemPrc?: {
        salestrNo: string;
        sellprc: number;
        aplStrtDts: string;
      };
    }>;
    b2ePrcAplTgts?: Array<{
      b2ePrcAplTgt?: {
        salestrNo: string;
        b2eMbrcoId: string;
        b2eSellprc: number;
      };
    }>;
    salestrBaseInvQtys?: Array<{
      salestrInv?: {
        salestrNo: string;
        baseInvQty: number;
      };
    }>;
    invQtyMarkgYn?: string;
    rsvSaleInfo?: {
      aplStrtDt: string;
      aplEndDt: string;
      whoutStrtDt: string;
      rstctInvQty: number;
      rsvSaleEndTp: string;
    };
    itemSellTypeCd?: string;
    uitemAttr?: {
      uitemOptnChoiTypeCd1: string;
      uitemOptnExpsrTypeCd1: string;
      uitemOptnChoiTypeCd2?: string;
      uitemOptnExpsrTypeCd2?: string;
      uitemOptnChoiTypeCd3?: string;
      uitemOptnExpsrTypeCd3?: string;
      uitemOptnChoiTypeCd4?: string;
      uitemOptnExpsrTypeCd4?: string;
      uitemOptnChoiTypeCd5?: string;
      uitemOptnExpsrTypeCd5?: string;
    };
    uitems?: Array<{
      uitem?: {
        uitemId?: string;
        tempUitemId?: string;
        uitemOptnTypeNm1?: string;
        uitemOptnNm1?: string;
        uitemOptnTypeNm2?: string;
        uitemOptnNm2?: string;
        uitemOptnTypeNm3?: string;
        uitemOptnNm3?: string;
        uitemOptnTypeNm4?: string;
        uitemOptnNm4?: string;
        uitemOptnTypeNm5?: string;
        uitemOptnNm5?: string;
        sellStatCd?: string;
        salestrBaseInvQtys?: Array<{
          salestrInv?: {
            salestrNo: string;
            baseInvQty: number;
            rstctInvQty?: number;
          };
        }>;
        useYn: "Yes" | "No";
      };
    }>;
    uitemOptnAddts?: Array<{
      uitemOptnAddt: {
        uitemOptnNm: string;
        uitemOptnNo: string;
        uitemOptnIptTypeCd: string;
        dataFileNm: string;
        useYn: "Yes" | "No";
      };
    }>;
    itemOrdOptns?: Array<{
      itemOrdOptn?: {
        addOrdOptnSeq: string;
        addOrdOptnNm: string;
        delYn?: string;
      };
    }>;
    uitemPluralPrcs?: Array<{
      uitemPrc?: {
        tempUitemId?: string;
        uitemId?: string;
        salestrNo: string;
        sellprc: number;
        prcDivCd: number;
      };
    }>;
    chgUitemPluralPrcs?: Array<{
      uitemPrc?: {
        tempUitemId?: string;
        uitemId?: string;
        salestrNo: string;
        sellprc: number;
        prcDivCd: number;
      };
    }>;
    returnUitemPluralPrcs?: Array<{
      uitemPrc?: {
        tempUitemId?: string;
        uitemId?: string;
        salestrNo: string;
        sellprc: number;
      };
    }>;
    shppItemDivCd?: string;
    exprtCntryId?: string;
    retExchPsblYn?: string;
    mareaShppYn?: string;
    jejuShppDisabYn: string;
    ismtarShppDisabYn: string;
    shppRqrmDcnt?: number;
    shppRqrmDcntChngRsnCntt?: string;
    splVenItemId?: string;
    itemTotWgt?: number;
    hopeShppDdDivCd?: string;
    hopeShppDdEndDts?: string;
    itemImgs?: Array<{
      imgInfo?: {
        dataSeq: number;
        dataFileNm: string;
        rplcTextNm: string;
        delYn?: string;
      };
    }>;
    qualityViewImgs?: Array<{
      imgInfo?: {
        dataSeq: number;
        dataFileNm: string;
        rplcTextNm: string;
        delYn?: string;
      };
    }>;
    itemDesc?: string;
    sizeDesc?: string;
    purchGuideCntt?: string;
    asMemoCntt?: string;
    qualityFiles?: Array<{
      qualityFile?: {
        itemDescDivCd: string;
        imgFileNm: string;
        delYn?: string;
      };
    }>;
    certificationProps?: Array<{
      prop?: {
        itemAppePropClsId: string;
        itemAppePropId: string;
        itemAppePropCntt: string;
      };
    }>;
    giftPsblYn?: string;
    shppMsgId?: string;
    vodExtnlPathUrl?: string;
    palimpItemYn?: string;
    itemSellWayCd?: string;
    itemStatTypeCd?: string;
    whinNotiYn?: string;
    fstPriceInfo?: {
      fstSellprc?: number;
      dataFileNm?: string;
    };
    book?: {
      isbn?: string;
      isbnExtensClsCd?: string;
      bookEngNm?: string;
      ortitlNm?: string;
      subtitlNm?: string;
      authorNm?: string;
      trltpeNm?: string;
      pubscoNm?: string;
      pageCntCntt?: string;
      pubsDt?: string;
      fxprc?: number;
      fxprcCurrCd?: string;
      appxBeingYn?: string;
      appxCntt?: string;
      tbcnttCntt?: string;
      authorIntroCntt?: string;
      trltpeIntroCntt?: string;
      prfaceCntt?: string;
      pubscoBkrevwCntt?: string;
      bookFxprcRegmAplYn?: string;
      bookItemDivCd?: string;
      limitGrdNm?: string;
      etcCntt?: string;
      addGuideCntt?: string;
      sellScr?: number;
      bookCpnNo?: string;
      bookCpnDcAmt?: number;
    };
    tags?: Array<{
      tag?: {
        tagNm?: string;
        delYn?: string;
      };
    }>;
    luxprGantItemYn?: string;
  };
};

export type UpdateDeptItemResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    uitems?: Array<{
      uitem?: {
        uitemId: string;
        uitemOptnTypeNm1: string;
        uitemOptnNm1: string;
        uitemOptnTypeNm2?: string;
        uitemOptnNm2?: string;
        uitemOptnTypeNm3?: string;
        uitemOptnNm3?: string;
        uitemOptnTypeNm4?: string;
        uitemOptnNm4?: string;
        uitemOptnTypeNm5?: string;
        uitemOptnNm5?: string;
        useYn: "Yes" | "No";
        salestrBaseInvQtys?: Array<{
          salestrInv?: {
            salestrNo: string;
            baseInvQty: number;
            rstctInvQty?: number;
          };
        }>;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: UpdateDeptItemRequestParams): Promise<Response<UpdateDeptItemResponseParams>> {
    return await this.client<UpdateDeptItemResponseParams>("item/0.2/updateDeptItem.ssg", {
      method: "post",
      json: params,
    });
  }
}
