// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type UpdateItemAppePropRequestParams = {
  updateItemAppeProp?: {
    itemId: string;
    itemAppeAttrs?: Array<{
      itemAppeAttr?: {
        itemAppePropId: string;
        itemAppePropCntt: string;
      };
    }>;
  };
};

export type UpdateItemAppePropResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: UpdateItemAppePropRequestParams): Promise<Response<UpdateItemAppePropResponseParams>> {
    return await this.client<UpdateItemAppePropResponseParams>("itemAttr/0.1/updateItemAppeProp.ssg", {
      method: "post",
      json: params,
    });
  }
}
