// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListDispCtgRequestParams = { stdCtgDclsId: string; siteNo?: string; page?: number; pageSize?: number };

export type ListDispCtgResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    dispCtgs?: Array<{
      ctg?: {
        siteNo: string;
        dispCtgClsCd: string;
        dispCtgClsNm: string;
        dispCtgLclsId: string;
        dispCtgLclsNm: string;
        dispCtgMclsId: string;
        dispCtgMclsNm: string;
        dispCtgSclsId: string;
        dispCtgSclsNm: string;
        dispCtgDclsId?: string;
        dispCtgDclsNm?: string;
        dispCtgSdclsId?: string;
        dispCtgSdclsNm?: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListDispCtgRequestParams): Promise<Response<ListDispCtgResponseParams>> {
    return await this.client<ListDispCtgResponseParams>("common/0.2/listDispCtg.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
