// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListItemMngPropRequestParams = { itemMngPropClsId?: string; stdCtgId?: string };

export type ListItemMngPropResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    itemMngPropClss?: Array<{
      itemMngPropCls?: {
        itemMngPropClsId: string;
        itemMngPropClsNm: string;
        itemMngPropId: string;
        itemMngPropNm: string;
        iptMthdCd: string;
        refCommCdClsId: string;
        mndtyYn: string;
        dispPrioyExpsrYn: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListItemMngPropRequestParams): Promise<Response<ListItemMngPropResponseParams>> {
    return await this.client<ListItemMngPropResponseParams>("common/0.1/listItemMngProp.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
