// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type GetVenShppMsgListRequestParams = {
  msgId: string;
  msgNm: string;
  useYn: "Yes" | "No";
  page?: number;
  pageSize?: number;
};

export type GetVenShppMsgListResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    venShppMsgs?: Array<{
      venShppMsg?: {
        msgId: string;
        venId: string;
        msgNm: string;
        aplStrtDt: string;
        aplEndDt: string;
        useYn: "Yes" | "No";
        htmlCntt: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: GetVenShppMsgListRequestParams): Promise<Response<GetVenShppMsgListResponseParams>> {
    return await this.client<GetVenShppMsgListResponseParams>("venInfo/0.1/getVenShppMsgList.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
