// THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.
// Edit generator/client-generator.ts if you want to make any changes.
import type { Response } from "got";
import { BaseClient } from "../client";

export type ListShppcstPlcyRequestParams = { shppcstId?: string; shppcstPlcyDivCd?: string; shppcstAplYn?: string };

export type ListShppcstPlcyResponseParams = {
  result: {
    resultCode: string;
    resultMessage: string;
    resultDesc: string;
    shppcstPlcys?: Array<{
      shppcstPlcy?: {
        shppcstPlcyDivCd: string;
        shppcstId: string;
        prpayCodDivCd: string;
        shppcstAplUnitCd: string;
        shppcst: number;
        shppcstExmpCritnAmt: number;
        bascPlcyYn: string;
        shppcstAplYn: string;
        shppcstCntt?: string;
      };
    }>;
  };
};

// render client
export class Client extends BaseClient {
  public async call(params: ListShppcstPlcyRequestParams): Promise<Response<ListShppcstPlcyResponseParams>> {
    return await this.client<ListShppcstPlcyResponseParams>("venInfo/0.1/listShppcstPlcy.ssg", {
      method: "get",
      searchParams: params,
    });
  }
}
